/**
 * RPG Maker MZ Default Templates
 * Ported from ShunsukeHayashi/rpgmaker-mz-mcp (MIT License)
 * Adapted for MCP SDK v1.0 + FileHandler/SafeWriter architecture
 */

export function getDefaultSystem(gameTitle: string) {
    return {
        gameTitle,
        versionId: 1,
        locale: "ja_JP",
        partyMembers: [1],
        currencyUnit: "G",
        windowTone: [0, 0, 0, 0],
        attackMotions: [
            { type: 0, weaponImageId: 0 },
            { type: 1, weaponImageId: 1 },
            { type: 1, weaponImageId: 2 },
            { type: 1, weaponImageId: 3 },
            { type: 1, weaponImageId: 4 },
            { type: 1, weaponImageId: 5 },
            { type: 1, weaponImageId: 6 },
            { type: 2, weaponImageId: 7 },
            { type: 2, weaponImageId: 8 },
            { type: 2, weaponImageId: 9 },
            { type: 0, weaponImageId: 10 },
            { type: 0, weaponImageId: 11 },
            { type: 0, weaponImageId: 12 },
        ],
        battleBgm: { name: "Battle1", pan: 0, pitch: 100, volume: 90 },
        battleEndMe: { name: "Victory1", pan: 0, pitch: 100, volume: 90 },
        defeatMe: { name: "Defeat1", pan: 0, pitch: 100, volume: 90 },
        gameoverMe: { name: "Gameover1", pan: 0, pitch: 100, volume: 90 },
        titleBgm: { name: "Theme1", pan: 0, pitch: 100, volume: 90 },
        boat: { bgm: { name: "Ship1", pan: 0, pitch: 100, volume: 90 }, characterIndex: 0, characterName: "Vehicle", startMapId: 0, startX: 0, startY: 0 },
        ship: { bgm: { name: "Ship2", pan: 0, pitch: 100, volume: 90 }, characterIndex: 1, characterName: "Vehicle", startMapId: 0, startX: 0, startY: 0 },
        airship: { bgm: { name: "Ship3", pan: 0, pitch: 100, volume: 90 }, characterIndex: 2, characterName: "Vehicle", startMapId: 0, startX: 0, startY: 0 },
        title1Name: "Castle",
        title2Name: "",
        optDisplayTp: true,
        optDrawTitle: true,
        optTransparent: false,
        optFollowers: true,
        optSlipDeath: false,
        optFloorDeath: false,
        optSideView: false,
        optExtraExp: false,
        titleCommandWindow: { background: 0, offsetX: 0, offsetY: 0 },
        startMapId: 1,
        startX: 0,
        startY: 0,
        hasEncryptedImages: false,
        hasEncryptedAudio: false,
        terms: {
            basic: ["レベル", "Lv", "HP", "HP", "MP", "MP", "TP", "TP", "EXP", "EXP"],
            commands: ["戦う", "逃げる", "攻撃", "防御", "アイテム", "スキル", "装備", "ステータス", "並び替え", "セーブ", "ゲーム終了", "オプション", "武器", "防具", "大事なもの", "装備", "最強装備", "全て外す", "ニューゲーム", "コンティニュー", null, "タイトルへ", "やめる"],
            params: ["最大HP", "最大MP", "攻撃力", "防御力", "魔法力", "魔法防御", "敏捷性", "運"],
            messages: {
                actionFailure: "しかし %1 には効かなかった！",
                actorDamage: "%1 は %2 のダメージを受けた！",
                actorDrain: "%1 は %2 の %3 を奪った！",
                actorGain: "%1 の %2 が %3 上がった！",
                actorLoss: "%1 の %2 が %3 下がった！",
                actorNoDamage: "%1 はダメージを受けていない！",
                actorNoHit: "ミス！ %1 はダメージを受けていない！",
                actorRecovery: "%1 の %2 が %3 回復した！",
                alwaysDash: "常時ダッシュ",
                bgmVolume: "BGM 音量",
                bgsVolume: "BGS 音量",
                buffAdd: "%1 の %2 が上がった！",
                buffRemove: "%1 の %2 が元に戻った！",
                commandRemember: "コマンド記憶",
                counterAttack: "%1 の反撃！",
                criticalToActor: "痛恨の一撃！",
                criticalToEnemy: "会心の一撃！",
                debuffAdd: "%1 の %2 が下がった！",
                defeat: "%1 は倒れた。",
                emerge: "%1 が出現！",
                enemyDamage: "%1 に %2 のダメージを与えた！",
                enemyDrain: "%1 の %2 を %3 奪った！",
                enemyGain: "%1 の %2 が %3 上がった！",
                enemyLoss: "%1 の %2 が %3 下がった！",
                enemyNoDamage: "%1 にダメージを与えられない！",
                enemyNoHit: "ミス！ %1 にダメージを与えられない！",
                enemyRecovery: "%1 の %2 が %3 回復した！",
                escapeFailure: "しかし逃げることはできなかった！",
                escapeStart: "%1 は逃げ出した！",
                evasion: "%1 は攻撃をかわした！",
                expNext: "次の %1 まで",
                expTotal: "現在の %1",
                file: "ファイル",
                levelUp: "%1 は %2 %3 に上がった！",
                loadMessage: "どのファイルをロードしますか？",
                magicEvasion: "%1 は魔法を打ち消した！",
                magicReflection: "%1 は魔法を跳ね返した！",
                meVolume: "ME 音量",
                obtainExp: "%1 の %2 を獲得！",
                obtainGold: "お金を %1\\G 手に入れた！",
                obtainItem: "%1 を手に入れた！",
                obtainSkill: "%1 を覚えた！",
                partyName: "%1 たち",
                possession: "持っている数",
                preemptive: "%1 は先手を取った！",
                saveMessage: "どのファイルにセーブしますか？",
                seVolume: "SE 音量",
                substitute: "%1 が %2 をかばった！",
                surprise: "%1 は不意をつかれた！",
                useItem: "%1 は %2 を使った！",
                victory: "%1 の勝利！",
            },
        },
        testBattlers: [],
        testTroopId: 1,
        battleback1Name: "",
        battleback2Name: "",
        battlerName: "",
        battlerHue: 0,
        editMapId: 1,
        menuCommands: [true, true, true, true, true, true],
        skillTypes: ["", "魔法", "必殺技"],
        weaponTypes: ["", "短剣", "剣", "フレイル", "斧", "ムチ", "杖", "弓", "クロスボウ", "銃", "爪", "グローブ", "槍"],
        armorTypes: ["", "汎用", "魔法防具", "軽装鎧", "重装鎧", "小型盾", "大型盾"],
        equipTypes: ["武器", "盾", "頭", "身体", "装飾品"],
        elements: ["", "物理", "炎", "氷", "雷", "水", "土", "風", "光", "闇"],
        switches: [""],
        variables: [""],
        magicSkills: [1],
        advanced: {
            gameId: Math.floor(Math.random() * 100000000),
            screenWidth: 816,
            screenHeight: 624,
            uiAreaWidth: 816,
            uiAreaHeight: 624,
        },
    };
}

export const PROJECT_DIRECTORIES = [
    "audio/bgm", "audio/bgs", "audio/me", "audio/se",
    "data", "effects",
    "img/animations", "img/battlebacks1", "img/battlebacks2",
    "img/characters", "img/enemies", "img/faces",
    "img/parallaxes", "img/pictures", "img/sv_actors", "img/sv_enemies",
    "img/system", "img/tilesets", "img/titles1", "img/titles2",
    "js/plugins", "movies",
];

export const EMPTY_DATABASE_FILES = [
    "Actors.json", "Classes.json", "Skills.json", "Items.json",
    "Weapons.json", "Armors.json", "Enemies.json", "Troops.json",
    "States.json", "Animations.json", "Tilesets.json", "CommonEvents.json",
];

export const ASSET_SPECS: Record<string, { width: number; height: number; grid?: string; dir: string }> = {
    character:  { width: 144, height: 192, grid: "3x4",       dir: "img/characters" },
    face:       { width: 144, height: 144, grid: "2x2",       dir: "img/faces" },
    tileset:    { width: 768, height: 768, grid: "24x24 tiles", dir: "img/tilesets" },
    battleback: { width: 1000, height: 740,                    dir: "img/battlebacks1" },
    enemy:      { width: 816, height: 624,                     dir: "img/enemies" },
    sv_actor:   { width: 576, height: 384, grid: "9x6",       dir: "img/sv_actors" },
    picture:    { width: 816, height: 624,                     dir: "img/pictures" },
};
